language: java

jdk:
  - oraclejdk8

notifications:
  email: false

before_install:
 - chmod +x gradlew

install:
  - ./gradlew setupCIWorkspace -S

script:
  - ./gradlew build -S

env:
  global:
    TERM=dumb

sudo: false
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper

git:
  depth: 1